### ISSUE TITLE
Special chars are breaking note content

### ISSUE THREAD

**Issue by Lowess** [osminogin/tornote#1]
While using Tornote, I realized that some special chars are breaking a note.

Something like:
![image](https://cloud.githubusercontent.com/assets/1719652/22096412/3711209c-ddd0-11e6-997e-2c6a8a4d4d51.png)

Will result in:
![image](https://cloud.githubusercontent.com/assets/1719652/22096419/4174630a-ddd0-11e6-9e9a-8b8124ddc67e.png)

As you can see the use of the char `<` in the middle of a word breaks the rest of the message `MySuperPassword` is gone.

Do you have any thoughts ?

**Comment by osminogin** [comment]
Also, www.tornote.xyz updated.

Thanks for bug report.

**Comment by Lowess** [comment]
Thanks a lot! I can confirm it's all fixed. I just upgraded our production Tornote server.
